### ISSUE TITLE
Error when tweet with media

### ISSUE THREAD

**Issue by h3poteto** [h3poteto/whalebird.server#100]
```
A Twitter::Error::UnacceptableIO occurred in apis#tweet:

  The IO object for media must respond to to_io
  app/controllers/users/apis_controller.rb:113:in `tweet'


-------------------------------
Request:
-------------------------------

  * URL        : https://api.whalebird.org/users/apis/tweet.json
  * HTTP Method: POST
  * IP address : 106.129.211.179
  * Parameters : {"settings"=>{"medias"=>["4f66bc8fd9836c7a44d7222ab07a8e19.png"]}, "status"=>"温泉、鯉、ビール。", "controller"=>"users/apis", "action"=>"tweet", "format"=>"json"}
  * Timestamp  : 2017-08-14 19:36:59 +0900
  * Server : whalebird-production
  * Rails root : /srv/www/whalebird.server/releases/20170805153847
  * Process: 14100


-------------------------------
Backtrace:
-------------------------------

  app/controllers/users/apis_controller.rb:113:in `tweet'
```

**Comment by h3poteto** [comment]
Now I use `update_with_media`, but this endpoint does not support multiple images. So, use image upload and `update` for tweet with multipe images.
https://dev.twitter.com/rest/reference/post/statuses/update_with_media
http://www.rubydoc.info/gems/twitter/Twitter/REST/Tweets#update-instance_method
