### ISSUE TITLE
An EOFError occurred in background at 2015-05-20 06:20:39 +0900 :

### ISSUE THREAD

**Issue by h3poteto** [h3poteto/whalebird.server#13]
end of file reached
  /home/ubuntu/.rbenv/versions/2.1.3/lib/ruby/2.1.0/openssl/buffering.rb:129:in `sysread'

  -------------------------------
Backtrace:
-------------------------------

  /home/ubuntu/.rbenv/versions/2.1.3/lib/ruby/2.1.0/openssl/buffering.rb:129:in `sysread'
  /home/ubuntu/.rbenv/versions/2.1.3/lib/ruby/2.1.0/openssl/buffering.rb:129:in `readpartial'
  /srv/www/whalebird.server/shared/bundle/ruby/2.1.0/bundler/gems/twitter-2caff0be3cd7/lib/twitter/streaming/connection.rb:22:in `stream'
  /srv/www/whalebird.server/shared/bundle/ruby/2.1.0/bundler/gems/twitter-2caff0be3cd7/lib/twitter/streaming/client.rb:119:in `request'
  /srv/www/whalebird.server/shared/bundle/ruby/2.1.0/bundler/gems/twitter-2caff0be3cd7/lib/twitter/streaming/client.rb:93:in `user'
  /srv/www/whalebird.server/releases/20150519165650/app/workers/userstream_worker.rb:28:in `perform'
  /srv/www/whalebird.server/shared/bundle/ruby/2.1.0/gems/sidekiq-3.2.6/lib/sidekiq/processor.rb:75:in `execute_job'
  /srv/www/whalebird.server/shared/bundle/ruby/2.1.0/gems/sidekiq-3.2.6/lib/sidekiq/processor.rb:52:in `block (2 levels) in process'
  /srv/www/whalebird.server/shared/bundle/ruby/2.1.0/gems/sidekiq-3.2.6/lib/sidekiq/middleware/chain.rb:122:in `call'
  /srv/www/whalebird.server/shared/bundle/ruby/2.1.0/gems/sidekiq-3.2.6/lib/sidekiq/middleware/chain.rb:122:in `block in invoke'
  /srv/www/whalebird.server/shared/bundle/ruby/2.1.0/gems/sidekiq-3.2.6/lib/sidekiq/middleware/server/active_record.rb:6:in `call'
  /srv/www/whalebird.server/shared/bundle/ruby/2.1.0/gems/sidekiq-3.2.6/lib/sidekiq/middleware/chain.rb:124:in `block in invoke'
  /srv/www/whalebird.server/shared/bundle/ruby/2.1.0/gems/sidekiq-3.2.6/lib/sidekiq/middleware/server/retry_jobs.rb:74:in `call'
  /srv/www/whalebird.server/shared/bundle/ruby/2.1.0/gems/sidekiq-3.2.6/lib/sidekiq/middleware/chain.rb:124:in `block in invoke'
  /srv/www/whalebird.server/shared/bundle/ruby/2.1.0/gems/sidekiq-3.2.6/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'
  /srv/www/whalebird.server/shared/bundle/ruby/2.1.0/gems/sidekiq-3.2.6/lib/sidekiq/logging.rb:22:in `with_context'
  /srv/www/whalebird.server/shared/bundle/ruby/2.1.0/gems/sidekiq-3.2.6/lib/sidekiq/middleware/server/logging.rb:7:in `call'
  /srv/www/whalebird.server/shared/bundle/ruby/2.1.0/gems/sidekiq-3.2.6/lib/sidekiq/middleware/chain.rb:124:in `block in invoke'
  /srv/www/whalebird.server/shared/bundle/ruby/2.1.0/gems/sidekiq-3.2.6/lib/sidekiq/middleware/chain.rb:127:in `call'
  /srv/www/whalebird.server/shared/bundle/ruby/2.1.0/gems/sidekiq-3.2.6/lib/sidekiq/middleware/chain.rb:127:in `invoke'
  /srv/www/whalebird.server/shared/bundle/ruby/2.1.0/gems/sidekiq-3.2.6/lib/sidekiq/processor.rb:51:in `block in process'
  /srv/www/whalebird.server/shared/bundle/ruby/2.1.0/gems/sidekiq-3.2.6/lib/sidekiq/processor.rb:98:in `stats'
  /srv/www/whalebird.server/shared/bundle/ruby/2.1.0/gems/sidekiq-3.2.6/lib/sidekiq/processor.rb:50:in `process'
  /srv/www/whalebird.server/shared/bundle/ruby/2.1.0/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `public_send'
  /srv/www/whalebird.server/shared/bundle/ruby/2.1.0/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `dispatch'
  /srv/www/whalebird.server/shared/bundle/ruby/2.1.0/gems/celluloid-0.15.2/lib/celluloid/calls.rb:122:in `dispatch'
  /srv/www/whalebird.server/shared/bundle/ruby/2.1.0/gems/celluloid-0.15.2/lib/celluloid/actor.rb:322:in `block in handle_message'
  /srv/www/whalebird.server/shared/bundle/ruby/2.1.0/gems/celluloid-0.15.2/lib/celluloid/actor.rb:416:in `block in task'
  /srv/www/whalebird.server/shared/bundle/ruby/2.1.0/gems/celluloid-0.15.2/lib/celluloid/tasks.rb:55:in `block in initialize'
  /srv/www/whalebird.server/shared/bundle/ruby/2.1.0/gems/celluloid-0.15.2/lib/celluloid/tasks/task_fiber.rb:13:in `block in create'

-------------------------------
Data:
-------------------------------

  * data: {}

**Comment by h3poteto** [comment]
twitter gemをアップデートしてみる

**Comment by h3poteto** [comment]
twitter gemの最新コミットにてproxyが積まれており，ここでエラー発生のため，バージョンアップは中止
